services:
  ###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - '1025:1025'
      - '8025:8025'
    labels:
      com.symfony.server.service-ignore: true
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  ###> Database ###
  database:
    image: mysql:8.0
    container_name: kopeck-db-local
    restart: unless-stopped
    ports:
      - '3308:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - db-config:/etc/mysql

volumes:
  mysql_data:
  db-config:
